In [1]:
import numpy as np

In [2]:
H = np.array([[0.1, 0.5, 1.0],
              [0.11, 0.1, 0.11],
              [1.0, 0.5, 0.1]])

In [32]:
# define f
f = np.array([1,0,0])

print(f.shape)

(3,)


In [33]:
U, S, VT = np.linalg.svd(H)

In [34]:
U, S, VT

(array([[-7.00140042e-01,  7.07106781e-01,  9.90147543e-02],
        [-1.40028008e-01, -1.74272567e-16, -9.90147543e-01],
        [-7.00140042e-01, -7.07106781e-01,  9.90147543e-02]]),
 array([1.32068164e+00, 9.00000000e-01, 2.15690850e-16]),
 array([[-5.94811877e-01, -5.40738070e-01, -5.94811877e-01],
        [-7.07106781e-01,  6.05743167e-17,  7.07106781e-01],
        [ 3.82359556e-01, -8.41191024e-01,  3.82359556e-01]]))

In [35]:
S

array([1.32068164e+00, 9.00000000e-01, 2.15690850e-16])

In [36]:
# compute g = Hf
g = np.matmul(H,f)

print(g, g.shape)

[0.1  0.11 1.  ] (3,)


In [37]:
# compute the pseudo inverse of H
S_t_diag = np.diag(S[0:2])
VT_t = VT[0:2,:]
U_t = U[:,0:2] 
inv_of_ST_times_S = np.linalg.inv(np.matmul(S_t_diag.T,S_t_diag))
H_pinv = np.matmul(np.matmul(np.matmul(VT_t.T,inv_of_ST_times_S),S_t_diag.T),U_t.T)

In [38]:
f_hat = np.matmul(H_pinv,g)

In [39]:
print(f_hat)

[ 0.85380117  0.32163743 -0.14619883]
